# Generated by Django 4.2.1 on 2023-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_testgroup_quiz_test_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
